const products = [
  {
    id: 1,
    name: "Laptop",
    brand: "Dell",
    category: "Electronics",
    price: "800$",
    count: 1,
    image: "/src/assets/dell.svg",
  },
  {
    id: 2,
    name: "Phone",
    brand: "Samsung",
    category: "Electronics",
    price: "250$",
    count: 1,
    image: "/src/assets/sphone.svg",
  },
  {
    id: 4,
    name: "iPad",
    brand: "Apple",
    category: "Electronics",
    price: "500$",
    count: 0,
    image: "/src/assets/tablet.svg",
  },
  {
    id: 5,
    name: "Laptop",
    brand: "Lenovo",
    category: "Electronics",
    price: "1000$",
    count: 3,
    image: "/src/assets/laptop.svg",
  },
  {
    id: 6,
    name: "Microphone",
    brand: "Blue Yeti",
    category: "Accessories",
    price: "200$",
    count: 2,
    image: "/src/assets/microphone.svg",
  },
  {
    id: 7,
    name: "Headphones",
    brand: "Sony",
    category: "Accessories",
    price: "300$",
    count: 6,
    image: "/src/assets/headphones.svg",
  },
];

export default products;
